### ISSUE TITLE
Cleanup stale tmp files in tmp2

### ISSUE THREAD

**Issue by efnats** [guydavis/machinaris#173] opened 2021-07-13 10:47 UTC
In Machinaris V0.5 707f600 testing stale *.tmp files don't get cleaned up in tmp2 directory which is used in madmax for plotting in ram.
This results in the plotter failing to start.

The issue is related to https://github.com/guydavis/machinaris/issues/7

**Comment by guydavis** [comment] 2021-07-15 22:20
Good suggestion.  Just added, will be in test version shortly.

**Comment by ray-su** [comment] 2021-07-16 16:08
Mine won't delete any tmp files after killing a plotting job.  I'm running it in Docker. in Unraid.

**Comment by guydavis** [comment] 2021-07-16 18:24
Good suggestion.  I've just added this code for 

> Mine won't delete any tmp files after killing a plotting job. I'm running it in Docker. in Unraid.

Thanks for the report.  Looks like a regression in plotman.  I'll deal with it in Machinaris.  In next release.

**Comment by guydavis** [comment] 2021-07-22 23:04
Now available in [v0.5.1 release](https://github.com/guydavis/machinaris/releases/tag/0.5.1).

**Closed by guydavis** 2021-07-22 23:04 UTC
Labels: bug, pending-release
